<?php
namespace FedExRestApi\OpenShipService\ComplexType;

use FedExRestApi\AbstractComplexType;

/**
 * These are export Detail used for US or CA exports.
 *
 * @author      Asabix
 * @package     PHP FedEx REST API wrapper
 *
 *
 * @property OpenShipDestinationControlDetail $destinationControlDetail
 * @property string $b13AFilingOption
 * @property string $exportComplianceStatement
 * @property string $permitNumber

 */
class OpenShipExportDetail extends AbstractComplexType
{
    /**
     * Name of this complex type
     *
     * @var string
     */
    protected $name = 'OpenShipExportDetail';

    /**
     * Set destinationControlDetail
     *
     *
     * Example:
     * @param OpenShipDestinationControlDetail $destinationControlDetail
     * @return $this
     */
    public function setDestinationControlDetail(OpenShipDestinationControlDetail $destinationControlDetail)
    {
        $this->values['destinationControlDetail'] = $destinationControlDetail;
        return $this;
    }

    /**
     * Get destinationControlDetail
     *
     * @return OpenShipDestinationControlDetail
     */
    public function getDestinationControlDetail()
    {
        return $this->values['destinationControlDetail'];
    }

    /**
     * Specify the filing option being exercised. Required for  non-document shipments originating in Canada destinated for any country other than Canada, the United States, Puerto Rico, or the U.S. Virgin Islands.
     *
     * simpleClass: OpenShipB13AFilingOption
     * Example: NOT_REQUIRED
     * @param string $b13AFilingOption
     * @return $this
     */
    public function setB13AFilingOption($b13AFilingOption)
    {
        $this->values['b13AFilingOption'] = $b13AFilingOption;
        return $this;
    }

    /**
     * Get b13AFilingOption
     *
     * @return string
     */
    public function getB13AFilingOption()
    {
        return $this->values['b13AFilingOption'];
    }

    /**
     * For US export shipments requiring an EEI, enter the ITN number received from AES when you filed your shipment or the FTR (Foreign Trade Regulations) exemption number.The proper format for an ITN number is AES XYYYYMMDDNNNNNN where YYYYMMDD is date and NNNNNN are numbers generated by the AES.<br> Example: AESX20220714987654<br>Note: The ITN or FTR exemption number you submit in the ship request prints on the international shipping label.<br><br>For CA export shipments,it can be Proof of report number(15-32 alphanumeric) ,Summary proof of report number(7-32 alphanumeric) or Exemption number(2 digit) based on the selected b13AFilingOption.<br>Example: 98765432107654321(POR number), 7654321(Summary POR number) and 02(Exemption number).<br>For FTR exemption number you need provide a predefined value as NO_EEI_30_37_A.
     *
     *
     * Example: 12345678901234567
     * @param string $exportComplianceStatement
     * @return $this
     */
    public function setExportComplianceStatement($exportComplianceStatement)
    {
        $this->values['exportComplianceStatement'] = $exportComplianceStatement;
        return $this;
    }

    /**
     * Get exportComplianceStatement
     *
     * @return string
     */
    public function getExportComplianceStatement()
    {
        return $this->values['exportComplianceStatement'];
    }

    /**
     * This is a Permit Number. This field is applicable only to Canada export non-document shipments of any value to any destination. No special characters are allowed.<br> Example: 12345
     *
     *
     * Example: 12345
     * @param string $permitNumber
     * @return $this
     */
    public function setPermitNumber($permitNumber)
    {
        $this->values['permitNumber'] = $permitNumber;
        return $this;
    }

    /**
     * Get permitNumber
     *
     * @return string
     */
    public function getPermitNumber()
    {
        return $this->values['permitNumber'];
    }
}
